# Generated by Django 4.1.7 on 2024-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(upload_to='preview_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
