# Generated by Django 4.1.7 on 2024-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Unknown', max_length=64),
            preserve_default=False,
        ),
    ]
