# Generated by Django 4.1.7 on 2024-03-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
